[package]
name = "blog-image"
version = "0.1.0"
authors = ["Amy Keibler <wanderingelf14@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.8"
imageproc = "0.21.0"
eyre = "0.6.0"
color-eyre = "0.5.1"
rusttype = "0.9.2"
toml = "0.5.6"
serde = { version = "1.0.115", features = ["derive"] }
rand = "0.7.3"
slug = "0.1.4"
conv = "0.3.3"

