[package]
name = "blog-image"
version = "0.1.0"
authors = ["Amy Keibler <wanderingelf14@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.14"
imageproc = "0.22.0"
eyre = "0.6.5"
color-eyre = "0.6.0"
rusttype = "0.9.2"
toml = "0.5.8"
serde = { version = "1.0.133", features = ["derive"] }
rand = "0.8.4"
slug = "0.1.4"
conv = "0.3.3"

